### ISSUE TITLE
Integrating with font-lock?

### ISSUE THREAD

**Issue by cpitclaudel** [ddoherty03/commify#2]
Could this be integrated with font-lock? Numbers would be given a display property that adds the separators, without actual modifications to the buffer.

**Comment by ddoherty03** [comment]
Not sure.  I'm no elisp expert, but a brief look made it seem as though only the face can be changed with font lock.

I like the idea, though.

**Comment by cpitclaudel** [comment]
> I like the idea, though.

Cool :) It's definitely feasible, and it should be pretty easy. Font-lock supports arbitrary text properties, not just face; Look at `prettify-symbols-mode`, `nameless`, or `glasses-mode`.

From the docs:

```
font-lock-keywords is a variable defined in ‘font-lock.el’.
...

Documentation:
A list of the keywords to highlight.
...

MATCH-HIGHLIGHT should be of the form:

 (SUBEXP FACENAME [OVERRIDE [LAXMATCH]])
...

FACENAME is an expression whose value is the face name to use.
Instead of a face, FACENAME can evaluate to a property list of
the form (face FACE PROP1 VAL1 PROP2 VAL2 ...)  in which case all
the listed text-properties will be set rather than just FACE.  In
such a case, you will most likely want to put those properties in
‘font-lock-extra-managed-props’ or to override
‘font-lock-unfontify-region-function’.
```

**Comment by ddoherty03** [comment]
I will.  Thanks for the pointer.



====================================================
Daniel E. Doherty
Law Offices of Daniel E. Doherty
7300 W. 110th Street, Suite 930
Overland Park, KS 66210
913.338.7182 (Phone)
913.338.7164 (FAX)
ded-law@ddoherty.net

**Comment by cpitclaudel** [comment]
Great, thanks!

**Comment by ddoherty03** [comment]
I am closing this as beyond the scope of the package, but thanks for the suggestion.
